export default [
  "iconcheliangshenqingbiao",
  "iconcaiwuyusuantiaozhengshenqingbiao",
  "icondangyuanzhengmingxinshenqing",
  "iconfuwujiandu",
  "icondangyuanxiaoneizuzhiguanxijiezhuanbiao",
  "icondanganliyongshenpibiao",
  "iconguangrongbangjianglishenqingbiao_",
  "icongerenganburenshidanganzhuandishenpidan",

  "iconganburenshidanganliyongshenpibiao",
  "iconguangdongshengzaizhizhigonghuzhubaozhangjihuahuzhujinshenqingbiao",
  "iconguangrongbangjianglishenqingbiao",
  "icongudingzichantiaoboshenqingdan",
  "iconguangkeyuansheyingshexiangshebeitiaopeishenqingbiao",
  "iconhengxiangwaixiexiangmuhetongshenpibiao",
  "iconjiaoxueshipinxinwenshipinpaishezhizuoshenqingbiao",
  "iconhuijidanganchaxunshenpibiao",

  "iconjiajushebeipiliangbanqianshenqingbiao",
  "iconjiaozhigongxiaojiashenpidan",
  "iconjiaozhigongqingjiashenpidanqita",
  "iconshengneichengyongfeigonggongjiaotonggongjuchuchashenpibiao",
  "iconjiaozhigongqingjiashenpidanchanjialei",
  "iconkeyanxiangmushenbaohezuoxieyishenpibiao",
  "icontushuguanbaloubaogaotingshenqingbiao",
  "iconshangwangmianrenzhengshenqingbiao",

  "iconshixunshixinxitianbaobiao",
  "iconxiaoneiduanqishangwangzhanghaoshenqingbiao",
  "iconweixiujilu",
  "iconxiangmukuzixiangmuyusuanxiadashenqingbiao",
  "iconshixunjidijianshexiangmulixiangshenqingdan",
  "iconxiaofeijilu",
  "iconwangzhanmenhushenqing",
  "iconxueshengxinlijiankangzhuangkuangzhoubaohuizong",

  "iconxingshiyuzhengcebaogaohuihezhexueshehuikexuebaogaohuiyantaohuijiangzuoluntanshenpibiao",
  "iconxinjianwangluoIPwangluoshenqingbiao",
  "iconxueshengchuyongyinshenqingbiao",
  "iconxinxishouji",
  "iconzhishichanquanshenqingshenpibiao",
  "iconxuexiaoxiaoyuanwangxinwenzixunfabushenpibiao",
  "iconzhichujiekuanyewushenpibiao",
  "iconyunziyuanyewushenqingbiao",

  "iconzuzhiguanxizhuanyishenqingbiaoxiaowai",
  "iconyikatong",
  "iconxitongshezhi",
  "iconzuoyefenpei",
  "iconrukusaomiao",
  "iconxiaoshouchukudansaomiaosvg",
  "iconzhongdaPOSxiaopiaosvg",
  "iconwuliuyunshuzhuangxiangsvg",
  "iconxianhuoxiaoshoudanluzhisvg",

  "iconzuoyefenpeisvg",
  "icontiaobochukuludansvg",
  "iconxianhuocaigoudingdanluzhisvg",
  "iconyidongPOSsvg",
  "icontiaobotongyongsvg",
  "icontiaobochukuzhuangxiangsvg",
  "iconxitongshezhisvg",
  "iconsaomiaorizhisvg",

  "icontiaoborukusaomiaosvg",
  "iconshujutongbusvg",
  "iconshoutuodaixiaotuihuodanluzhisvg",
  "iconqitachukusaomiaosvg",
  "iconqitagongnengsvg",
  "iconsaomagousvg",
  "iconpiliangjianhuodanshengxiaosvg",
  "iconqitarukusaomiaosvg",

  "iconlinjintiaochuquerensvg",
  "iconkucunchaxunsvg",
  "iconjianhuodanzhuangxiangsvg",
  "iconchunfengwuliugenzongsvg",
  "iconchimakuaijietuihuanhuosvg",
  "icondayinbozhongfenhuodansvg",
  "icondanjuqianshousvg",
  "iconjianyichuweiguanlidanhaosvg",

  "iconpandiandansvg",
  "iconrfidmendianzhaohuosvg",
  "iconcaigoutuihuochukusvg",
  "iconcaigoutuihuodanluzhisvg",
  "iconbiaoqiandayinsvg",
  "iconanxiangshoufenhuozuoyedansvg",
  "iconPOSxiaoshoushezhisvg",
  "iconquanqudaotongyongsvg",

  "iconjianyichuweiguanlisaomiaosvg",
  "iconrukuguanlisvg",
  "icontiaoboguanlisvg",
  "iconfenjianhuoguanlisvg",
  "iconhoucangguanlisvg",
  "iconsaomiaoguanlisvg",
  "iconchukuguanlisvg",
  "iconposxiaoshousvg",

  "iconcaigoudaohuorukusvg",
  "iconlinjintiaoborukusvg",
  "iconquanqudaodingdansvg",
  "icontiaoboshenqingchukusvg",
  "iconjianhuodanhebingzhuangxiangsvg",
  "iconquanqudaofuhesvg",
  "iconquanqudaoguanlisvg",
  "iconkucunyujingsvg",

  "icondengdaichukusvg",
  "icondengdairukusvg",
  "iconjingyingfenxisvg",
  "iconhoucangguanlisvg1",
  "iconchukuguanli_1svg",
  "icondanjuluzhi_1svg",
  "iconrukuguanli_1svg",
  "icontiaoboguanli_1svg",

  "iconchuweiguanlisvg",
  "iconquanqudaosvg",
  "icondanjuguanlisvg",
  "iconchukuguanli_1svg1",
  "iconrukuguanli_1svg1",
  "icondanjuluzhi_1svg1",
  "icondanjuguanlisvg1",
  "iconchuweiguanlisvg1",

  "icontiaoboguanli_1svg1",
  "iconquanqudaosvg1",
  "iconxiaoshouguanlisvg",
  "iconhoucangguanlisvg2",
  "iconhoucangguanlisvg3",
  "icondengdaichukusvg1",
  "icondengdairukusvg1",
  "iconyidongpossvg",
  "iconzuoyefenpeisvg1",

  "iconpandiandansvg1",
  "iconziyuan762",
  "iconchukuguanli",
  "icondanjuluzhi",
  "iconfenjianhuoguanli",
  "iconkucunyujing",
  "iconjingyingfenxi",
  "icondaibanshixiang",
  "iconsaomiaoguanli",

  "iconqianshou",
  "iconrukuguanli",
  "icontiaoboguanli",
  "iconkucunchaxun",
  "iconqitagongneng",
  "iconshujutongbu",
  "iconpandian",

  "iconyidongpos",
  "iconchukusaomiao"
]
