version: '3'
services:
  jvs-ui:
    build:
      context: .
    restart: always
    container_name: jvs-ui
    image: 0glg0/jvs-ui:${JVSVERSION}
    networks:
      - jvs_jvs
    external_links:
      - gateway
    ports:
      - 8080:80

networks:
  jvs_jvs:
    external: true
