export const formItemUrl =
  {
    Input: require(`./input/index.vue`).default,
    TextArea: require(`./textarea/index.vue`).default,
    InputNumber: require(`./inputNumber/index.vue`).default,
    Select: require(`./select/index.vue`).default,
    switchDoc: require(`./switch/index.vue`).default,
    Slider: require(`./slider/index.vue`).default,
    TimeSelect: require(`./timeSelect/index.vue`).default,
    TimePicker: require(`./timePicker/index.vue`).default,
    DatePicker: require(`./datePicker/index.vue`).default,
    Radio: require(`./radio/index.vue`).default,
    Checkbox: require(`./checkbox/index.vue`).default,
    ImageUpload: require(`./imageUpload/index.vue`).default,
    FileUpload: require(`./fileUpload/index.vue`).default,
    ColorSelect: require(`./colorSelect/index.vue`).default,
    IconSelect: require(`./iconSelect/index.vue`).default,
    Tab: require(`./tab/index.vue`).default,
    TableForm: require(`./tableForm/index.vue`).default,
    PCom: require(`./p/index.vue`).default,
    Divider: require(`./divider/index.vue`).default,
    ImageCom: require(`./image/index.vue`).default,
    FileCom: require(`./file/index.vue`).default,
    BoxCom: require(`./box/index.vue`).default,
    LinkCom: require(`./link/index.vue`).default,
    IframeCom: require(`./iframe/index.vue`).default,
    Department: require(`./department/index.vue`).default,
    Role: require(`./role/index.vue`).default,
    UserCom: require(`./user/index.vue`).default,
    PostCom: require(`./post/index.vue`).default,
    ChinaArea: require(`./chinaArea/index.vue`).default,
    Cascader: require(`./cascader/index.vue`).default,
    HtmlEditor: require(`./htmlEditor/index.vue`).default,
    DatasourceForm: require(`./datasource/index.vue`).default,
    StepBar: require(`./step/index.vue`).default,
    FormBox: require(`./formcard/index.vue`).default,
    ReportTable: require(`./reportTable/index.vue`).default
  }